### ISSUE TITLE
Slime fabricator produce "Air"

### ISSUE THREAD

**Issue by MokuJinJin** [MysticMods/MysticalPowers#2]
![2020-05-08_18 20 43](https://user-images.githubusercontent.com/5294669/81425953-ca92f680-9158-11ea-89bf-1ca6bfe73b4c.png)

this is done with OpenDevCraft v7.0.0

Mysticalpowers v0.0.0.1 / v0.0.0.2

**Comment by noobanidus** [comment]
I was afraid this would still happen. I wasn't unable to replicate it in my development enviornment or in my live environment to actually prove whether or not it had been fixed... I'm going to try something else, thanks!

**Comment by MokuJinJin** [comment]
Can you use opendevcraft modpack to debug it ?
In my screenshot, i've Just launch à single player with flat world, and use powah creative cell.

If I can help, please let me know.

**Comment by MokuJinJin** [comment]
Same test done with v0.0.0.4.
You must remove the old fabricator and replace it  to make it work.

Well done noobanidus.
